// Code generated by gen_handler_registry.go; DO NOT EDIT.
package handlers

import "github.com/gofiber/fiber/v2"

func init() {
	OperationRegistry = map[string]fiber.Handler{
		"RegisterHandler":    RegisterHandler,
		"TaskCreateHandler":  TaskCreateHandler,
		"PublicTasksHandler": PublicTasksHandler,
		"TaskDetailHandler":  TaskDetailHandler,
		"TaskUpdateHandler":  TaskUpdateHandler,
		"LoginHandler":       LoginHandler,
		"LogoutHandler":      LogoutHandler,
		"TasksListHandler":   TasksListHandler,
		"TaskDeleteHandler":  TaskDeleteHandler,
	}
}
