// Code generated by gen_handler_registry.go; DO NOT EDIT.
package handlers

import "net/http"

func init() {
	OperationRegistry = map[string]http.HandlerFunc{
		"LoginHandler": LoginHandler,
		"RegisterHandler": RegisterHandler,
		"TaskCreateHandler": TaskCreateHandler,
		"PublicTasksHandler": PublicTasksHandler,
		"TaskDetailHandler": TaskDetailHandler,
		"TaskUpdateHandler": TaskUpdateHandler,
		"LogoutHandler": LogoutHandler,
		"TasksListHandler": TasksListHandler,
		"TaskDeleteHandler": TaskDeleteHandler,
	}
}