//go:generate go run ../tools/gen_handler_registry.go
package handlers

import "net/http"

// OperationRegistry maps operationId to handler functions.
// This file should be generated by running `go generate ./handlers`.
var OperationRegistry map[string]http.HandlerFunc
