//go:generate go run ../tools/gen_handler_registry.go
package handlers

import "github.com/gofiber/fiber/v2"

// OperationRegistry maps operationId to handler functions.
// This file should be generated by running `go generate ./handlers`.
// OperationRegistry maps operationId to Fiber handler functions.
var OperationRegistry map[string]fiber.Handler
